# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-python:
    strategy:
      matrix:
        distro: ['fedora:latest', 'fedora:rawhide', 'opensuse:latest', 'ubuntu:latest', 'ubuntu:devel', 'ubuntu:rolling', 'fedora:intel']
        include:
          - distro: 'fedora:latest'
          - distro: 'fedora:nogmx'
          - distro: 'fedora:nogmx'
          - distro: 'fedora:nogmx'
          - distro: 'fedora:latest'
          - distro: 'fedora:intel'
          - distro: 'fedora:intel'
          - distro: 'fedora:intel'
          - distro: 'fedora:intel'
          - distro: 'fedora:gmx2019'
          - distro: 'fedora:gmx2019'
          - distro: 'fedora:gmx2019_d'
          - distro: 'fedora:gmx2019_d'
          - distro: 'fedora:gmx2021'
          - distro: 'fedora:gmx2021'
          - distro: 'fedora:gmx2021_d'
          - distro: 'fedora:gmx2021_d'
          - distro: 'fedora:gmx9999'
          - distro: 'fedora:gmx9999'
          - distro: 'fedora:gmx9999_d'
          - distro: 'fedora:gmx9999_d'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/votca/buildenv/${{ matrix.distro }}
        # https://bugzilla.redhat.com/show_bug.cgi?id=1900021
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: export
        run: export
      - name: lscpu
        run: lscpu
      - name: "test with: python3 test.py"
        run: python3 test.py
      - name: "test with: ./test.py"
        run: ./test.py
